# MIT License

# (C) Copyright [2022] Hewlett Packard Enterprise Development LP

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
name: Run Open-API Tavern Coverage
on: 
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on.
        type: string
        required: false
        default: ubuntu-latest
jobs:
  run_coverage:

    name: Run Coverage
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Run Open-API Tavern Coverage Tool
        shell: bash
        run: docker run -e GITHUB_TOKEN -e DRYRUN=false -v "$(realpath output):/output" artifactory.algol60.net/csm-docker/unstable/open-api-tavern-coverage:0.1.0
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.5
        with:
          # It is expected the that the open-api-tavern-coverage.md.tpl is present in this repo. Does it need to be in all repos? probably
          template: .github/open-api-tavern-coverage.md.tpl
          vars_path: ./output/job_summary_template_values.yaml

      - name: Job Summary
        run: echo '${{ steps.template.outputs.result }}' >> $GITHUB_STEP_SUMMARY